### ISSUE TITLE
integration testing: add sample for execute process

### ISSUE THREAD

**Issue by ppoetschke** [process-engine/process_engine_meta#10]
#### Describe your issue

Add a test for adding a bpmn process definition as fixture and executing it.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
I think we now have more than enough tests that cover this.
