### ISSUE TITLE
Add a script to control the Postgres docker container to the meta repo

### ISSUE THREAD

**Issue by robpal94** [process-engine/process_engine_meta#102]
#### Describe your issue
Currently, the only script to control the postgres docker container is a nodejs script, located in `skeleton/database`. If someone only wants to clone selected repositories from meta, he cant conveniently build, start and control the Postgres Docker container, without to clone the whole skeleton repo. This is needed, if the user wants to test his changes using the integration tests (since the local integration tests rely on a locally started Postgres server). 

I thought its a good Idea to add a control script for the postgres docker container, at least to the `_integraTests` directory to give users a chance to control the Postgres Docker Container without having to clone the Skeleton repo. 

I've already kinda done this in this Script: 
https://github.com/process-engine/process_engine_meta/blob/develop/_integration_tests/multiple_test_executions.bash

So exporting the used function wouldn't be that complex. 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
This should not be the responsibility of the meta package. Imho the script is best left in the skeleton repository.
