### ISSUE TITLE
Refactoring der Meta-Pakete

### ISSUE THREAD

**Issue by 5ebastianMeier** [process-engine/process_engine_meta#112]
#### Describe your issue

Inzwischen haben wir bei den Paketen ordentlich aufgeräumt und einige Domänen zeichnen sich bereits klar ab.

Ich würde das gerne demnächst nutzen, um die Art und Weise wie wir Meta Repositories schneiden und nutzen, zu aktualisieren.

Hierzu würde ich initial folgende Paketaufteilung vorschlagen:

### process_engine.io_meta
* documentation
* skeleton
* identity_server
* **bpmn-studio_meta**
* **process-engine_meta**
* **essential-projects_meta**
* **consumer-api_meta**
* **management-api_meta**
* **deployment-api_meta**
* **metrics-api_meta**
* **kpi-api_meta**
* **logging-api_meta**
* **token_history-api_meta**

### [bpmn-studio_meta](https://github.com/process-engine/bpmn-studio_meta)
* bpmn-studio
* bpmn-io_custom_bundle
* bpmn-studio_client (obsolete)

### essential_projects_meta
* bootstrapper
* bootstrapper_node
* bootstrapper_browser
* bootstrapper_contracts
* event_aggregator
* event_aggregator_contracts
* errors_ts
* http
* http_node
* http_extension
* iam_contracts
* sequelize_connection_manager
* services
* services_contracts
* timing
* timing_contracts
* tslint-config

### [process_engine_meta](https://github.com/process-engine/process_engine_meta)
* iam
* process_engine_core
* process_engine_contracts

### [persistence_api_meta](https://github.com/process-engine/persistence_api_meta)
* persistence_api_contracts
* correlation.repository.sequelize
* flow_node_instance.repository.sequelize
* logging.repository.file_system
* metrics.repository.file_system
* process_model.repository.sequelize
* timers.repository.sequelize

### [consumer_api_meta](https://github.com/process-engine/consumer_api_meta)
* consumer_api_client
* consumer_api_contracts
* consumer_api_core
* consumer_api_http

### [management_api_meta](https://github.com/process-engine/management_api_meta)
* management_api_client
* management_api_contracts
* management_api_core
* management_api_http

### [deployment_api_meta](https://github.com/process-engine/deployment_api_meta)
* deployment_api_contracts
* deployment_api_core
* deployment_api_http

### [kpi_api_meta](https://github.com/process-engine/kpi_api_meta)
* kpi_api_contracts
* kpi_api_core
* kpi_api_http

### [logging_api_meta](https://github.com/process-engine/logging_api_meta)
* logging_api_contracts
* logging_api_core
* logging_api_http

### [metrics_api_meta](https://github.com/process-engine/metrics_api_meta)
* metrics_api_contracts
* metrics_api_core

### [token_history_api_meta](https://github.com/process-engine/token_history_api_meta)
* token_history_api_contracts
* token_history_api_core
* token_history_api_http

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
2 Punkte würde ich evtl. ändern:

Würde aber `foundation_meta` einfach `essential-projects_meta` nennen, da dort ja scheinbar alle Essential Projects Pakete abgelegt werden. 
`iam_contracts` würde ich da auch auf jeden Fall sehen.

Ich würde auch denke ich `consumer-api_meta` und `management-api_meta` nicht bei `process-engine_meta` lagern, sondern eher direkt beim übergeordneten Meta Repo `process-engine.io_meta`.

Imho sind das getrennte Arbeitspakete und sollten auch getrennt liegen. Wenn ich z.B. an der Consumer API etwas implementiere, betrifft das ja auch nicht unmittelbar die Process Engine oder die Management API.

Sonst finde ich den Vorschlag gut. 👍

**Comment by 5ebastianMeier** [comment]
Mit dem Vorschlag `foundation_meta` > `essential-projects_meta` könnte ich gut leben. Die Absicht hinter dem Paket ist, die Pakete mit einer technischen Domäne (also ohne direkten fachlichen Bezug)  einzusortieren.

Bei `consumer-api_meta` und `management-api_meta` bin ich noch unsicher, in welchem Kontext die am besten platziert werden können.

Ggf. wäre es auch eine Option für diese APIs ein extra `api_meta` bzw. `process-engine-api_meta` abzustecken und dieses umschließende Paket stattdessen in `process-engine.io_meta` aufzunehmen.

**Comment by ElRaptorus** [comment]
@5ebastianMeier @cmg-dev @roblen45 Ich hab mal die neuen APIs in das vorgeschlagene Schema mit eingebettet. 
Sollten wir nochmal andiskutieren.
