### ISSUE TITLE
Update Master Branch

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/process_engine_meta#116]
#### Describe your issue

Unless there is still a need for supporting the old implementation, I think we should update the master branch asap, as that build frequently fails on jenkins, due to the old datastore adapter being unable to reliably connect to postgres.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
https://github.com/process-engine-pro/organization/issues/193

**Comment by 5ebastianMeier** [comment]
done
