### ISSUE TITLE
👷🏻‍♂️ :construction_worker: Update Jenkinsfiles in all Process-Engine Repos

### ISSUE THREAD

**Issue by cmg-dev** [process-engine/process_engine_meta#35]
#### Describe your issue

Update the Jenkinsfiles with the latest changes.

#34 needs to be done first.
#33 needs to be included as well.

**Please do two consecutive PRs!**

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Paulomart** [comment]
This is done.
