### ISSUE TITLE
👷 :constrution_worker: Use setGitHubPullRequestStatus to submit build status to GH

### ISSUE THREAD

**Issue by Paulomart** [process-engine/process_engine_meta#39]
#### Describe your issue

Currently Jenkins does this on its own. We should use the method to customize the message.

Also only one build is displayed, but two builds are run, this is because both have the same context.

#### Possible solution

Use `setGitHubPullRequestStatus`

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
@Paulomart Is this still an issue?

**Comment by Paulomart** [comment]
No

**Comment by Paulomart** [comment]
We can look at this in the future.
