### ISSUE TITLE
Integration Testing

### ISSUE THREAD

**Issue by 5ebastianMeier** [process-engine/process_engine_meta#6]
To improve stability and quality we need some form of integration tests that are run against our HTTP endpoint.

#### Possible solution

Proposal: use the folder `_integration_tests ` directly in the meta project for integration testing

The prefix `_` ensures that the folder is listed on top of cloned repositories.

The integration tests can be written in JavaScript using the framework `supertest`. It provides a fluent API to run tests against HTTP endpoints. Writing the tests in JavaScript and starting the test application through test tooling gives us the flexibility to use internal components if needed.

We also need sample bpmn files to use with these tests.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
Obsolete. 
This is replaced by https://github.com/process-engine-pro/organization/issues/109
