### ISSUE TITLE
Add integrationtest for ErrorEndEvent

### ISSUE THREAD

**Issue by 5ebastianMeier** [process-engine/process_engine_meta#81]
#### Describe your issue

Currently there is no test for the ErrorEndEvent.

The test needs to make sure that an ErrorEndEvent can be modeled with a concrete error.

For the error the properties `errorCode` and `name` can be supplied via the modeler.

If the ErrorEndEvent is reached, a JSON-object with the properties `errorCode` and `name` should be the result added to the process token. This result should also be returned to the process caller. 

The promise that is returned to the process caller gets **rejected** with the payload described above.

Possible test cases:

#### Regular process reaches ErrorEndEvent
This test case should just reject the promise returned to the caller and pass through the error payload.

#### Process called as a SubProcess reaches an ErrorEndEvent
This test case should use an ErrorBoundaryEvent attached to the SubProcess to catch the error that is referenced by the ErrorEndEvent.

Both - the ErrorBoundaryEvent and the ErrorEndEvent - have to reference the same error for this to work. 

The calling process should the follow the path of the ErrorBoundaryEvent.

#### Process called as a CallActivity reaches an ErrorEndEvent

This should look almost exactly like the SubProcess test case.

#### Further test cases for the ErrorBoundaryEvent

Because this marks the first time that the ErrorBoundaryEvent is going to handle only specific errors referenced by id, we also need tests for this scenario.

We need to make sure that only the referenced error triggers the ErrorBoundaryEvent, not just any error. If no error is referenced, then the current behavior should apply: handle any error occuring.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by robpal94** [comment]
See https://github.com/process-engine/process_engine_meta/pull/92

**Comment by robpal94** [comment]
> Because this marks the first time that the ErrorBoundaryEvent is going to handle only specific errors referenced by id, we also need tests for this scenario.

We need to make sure that only the referenced error triggers the ErrorBoundaryEvent, not just any error. If no error is referenced, then the current behavior should apply: handle any error occuring.

Aren't this general test cases for the error boundary event or the error event in general?
