### ISSUE TITLE
TerminateEndEvent test doesn't use new handlers

### ISSUE THREAD

**Issue by 5ebastianMeier** [process-engine/process_engine_meta#89]
#### Describe your issue

Currently the `TerminateEndEvent` erroneously uses the old handlers when executing the test process.

The reason for this error is, that this test performs multiple queries against the database.

For these queries the old implementation needed at least a `processInstanceId`. To get this `id`, it had to create a `processInstance` before executing it, so that the `id` generated on the server, is known to the caller.

#### Possible solution

To really fix this for the new implementation, the `consumer_api_core` (`ProcessEngineAdapter`) and the `TestFixtureProvider` contained in `process_engine_meta/_integration_tests` have to be updated to fully use the new object model.

We also need at least a rough implementation of the new `persistance` to be able to query for persisted results from within the integration tests.

This means this is blocked by:
* https://github.com/process-engine/consumer_api_core/issues/22
* and the concept for the new persistance (no issue yet)

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
https://github.com/process-engine-pro/organization/issues/72

**Comment by ElRaptorus** [comment]
https://github.com/process-engine-pro/organization/issues/171

**Comment by ElRaptorus** [comment]
I think this is best fixed, after we implemented the new persistence layer.

**Comment by ElRaptorus** [comment]
https://github.com/process-engine-pro/organization/issues/182
