### ISSUE TITLE
Timer boundary event tests fail on my local machine

### ISSUE THREAD

**Issue by robpal94** [process-engine/process_engine_meta#91]
#### Describe your issue
The timer boundary event tests fails on my local machine but not on the jenkins. 
Even with a _clean setup_, the timer boundary tests fails for me. It would be good, if someone who has some spare time could run the integration tests on his local machine and see, if some of the tests fails. 

#### How can others reproduce the issue?
Run `npm test` in the _integration_tests_ directory. 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
Is this still an issue for you? @robpal94

**Comment by robpal94** [comment]
Nope, they are working as intended.
